### ISSUE TITLE
Support creating a project from a directory in a GitHub repo

### ISSUE THREAD

**Issue by blaugold** [invertase/zapp.run#2]
**Is your feature request related to a problem? Please describe.**
Many projects have an example directory. It would be great if you could just point to it and have a Zapp project be populated with the files.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DFelten** [comment]
> I did have a question on this, would you expect an import to import all files in the directory or would you find it weird if it only selectively imports files that Zapp cares about (Dart & pub related files only) - e.g. ignoring android,ios,macos folders etc - since these can be large in some cases and OOM or reach project size limitations easily (currently 10mb)

When importing a GitHub Repository as a copy I think it would be ok to ignore such files or add them as a shortcut to the file in the corresponding Git repository.

**Comment by Salakar** [comment]
GitHub imports is now available (unannounced), e.g. 

 - https://zapp.run/github/roaa94/flutter_3d_calculator
 - https://zapp.run/github/roaa94/flutter_cool_card_swiper
 - https://zapp.run/github/rrousselGit/riverpod/tree/master/packages/flutter_riverpod/example

The url structure is the same as github.com urls, just replace github.com/ from the url with zapp.run/github/ and you're good to go. It supports branches/refs/commits/directories in a repo etc. There's no UI for it yet so testing can be done by visiting urls directly 😅

**Comment by guyluz11** [comment]
Nice job

Is it already in production?
I'm not sure where to find this option

**Comment by DFelten** [comment]
This is currently only possible for public repositories, right?

**Comment by Salakar** [comment]
> Nice job
> 
> Is it already in production? I'm not sure where to find this option

I explained above, see the example links, it's URL based currently

**Comment by DFelten** [comment]
Currently it seems, that Zapp.run does not work with repositories that contain multiple packages. 

For example, with one of mine I get the error that the project could not be loaded.

GitHub Repository: https://github.com/DFelten/robot_test

Zapp.run: https://zapp.run/github/DFelten/robot_test

**Comment by guyluz11** [comment]
@Salakar Thanks, I have missed that part.

> Currently it seems, that Zapp.run does not work with repositories that contain multiple packages.
> 
> For example, with one of mine I get the error that the project could not be loaded.
> 
> GitHub Repository: https://github.com/DFelten/robot_test
> 
> Zapp.run: https://zapp.run/github/DFelten/robot_test

Yep same with my repo https://zapp.run/github/CyBear-Jinni/cbj_app

**Comment by Salakar** [comment]
> Currently it seems, that Zapp.run does not work with repositories that contain multiple packages.
> 
> For example, with one of mine I get the error that the project could not be loaded.
> 
> GitHub Repository: [DFelten/robot_test](https://github.com/DFelten/robot_test)
> 
> Zapp.run: [zapp.run/github/DFelten/robot_test](https://zapp.run/github/DFelten/robot_test)

You can't import a whole repo that has no application in the root, you have to be explicit in specifying a url to a GitHub repo AND location where there's a Dart of Flutter application (if there's nothing that looks like an application in the root), e.g. https://zapp.run/github/DFelten/robot_test/tree/main/examples/robot_test - however this still won't work since there is no lib/main.dart file that indicates to Zapp that it's an application - in your case you will need to add one even if it just has an empty main function - since for you the test/ folder is the important part, and once imported you can specify running the test file through the drop down at the top right of Zapp:

![image](https://user-images.githubusercontent.com/5347038/213418331-18c840c9-a6ca-40ce-9211-1eb4125d65b0.png)

Changing the entry in this drop down also updates the url to say that this new file is the entry, so when you share your Zapp you can share it so it opens and runs tests directly instead (though there is a bug with this selector atm - cc @Ehesp)

These things will be documented soon.

----


> @Salakar Thanks, I have missed that part.
> 
> > Currently it seems, that Zapp.run does not work with repositories that contain multiple packages.
> > For example, with one of mine I get the error that the project could not be loaded.
> > GitHub Repository: [DFelten/robot_test](https://github.com/DFelten/robot_test)
> > Zapp.run: [zapp.run/github/DFelten/robot_test](https://zapp.run/github/DFelten/robot_test)
> 
> Yep same with my repo [zapp.run/github/CyBear-Jinni/cbj_app](https://zapp.run/github/CyBear-Jinni/cbj_app)

Hey, this should work for you; the reason it isn't is that there's a number of large pub packages in your pubspec, and our pub service caps running pub for a maximum of 30 seconds before it kills the process, I've increased it now to 60 seconds max running time which solved that problem, however, the other problem now is that Zapp does not support running build_runner and since you've not checked in your built files it's unable to import and build your project for you since it can't find certain files.

**Comment by guyluz11** [comment]
Thanks that is a good start, will create an issue for build_runner support.

**Comment by ramprasanna1** [comment]
> GitHub imports is now available (unannounced), e.g.
> 
> * https://zapp.run/github/roaa94/flutter_3d_calculator
> * https://zapp.run/github/roaa94/flutter_cool_card_swiper
> * https://zapp.run/github/rrousselGit/riverpod/tree/master/packages/flutter_riverpod/example
> * https://zapp.run/github/Yczar/solar-system
> 
> The url structure is the same as github.com urls, just replace github.com/ from the url with zapp.run/github/ and you're good to go. It supports branches/refs/commits/directories in a repo etc. There's no UI for it yet so testing can be done by visiting urls directly 😅

yeah but i try it your repositories only shown other repositories are not work

**Comment by NithikaManogaran** [comment]
zapp.run page is not available now .why? it show ERR_NAME_NOT_RESOLVED error
