### ISSUE TITLE
Files remain "unsaved" after Run

### ISSUE THREAD

**Issue by slovnicki** [invertase/zapp.run#35]
**Project ID:** flutter-zc406k9c506 
**Operating System & Version**: Ubuntu 20.04.4 LTS
**Browser & Version**: Chrome 101.0.4951.54

### Description

This may be intended, but to me was unexpected.

After changing some source file and running, everything runs fine, but "Save" remains clickable and "M" tag stays on the source file, although latest changes _were_ saved and built.

#### Reproduction Steps

- Edit a source file
- Don't press "Save"
- Press "Run"

In the image below, I changed "Flutter app" title into "Flutter a" and pressed "Run" button.
Observe that "M" tag on the file is still present and "Save" button enabled, after a successful build of changes.

![Screenshot from 2022-07-13 23-07-39](https://user-images.githubusercontent.com/29288059/178837260-aa4653a4-817c-4e1b-84bf-a93a141b3ee8.png)

**Comment by Ehesp** [comment]
Yeah this is currently the expected behaviour, however I'm not sure whether it is the correct behaviour.

Part of the issue we saw with running triggering a save, is say you're working on updating an existing project you want to build the results to check things are working as intended (they might not be). If its a popular project, you'd potentially be saving broken builds each time you run.

Happy to discuss this one as we want to make sure that the experience feels correct

**Comment by slovnicki** [comment]
Ah, I see.

Then it may be a good thing to have a "Save on Run" toggle that can be false by default.

We'll see what others think about this...

**Comment by Salakar** [comment]
This has been reworked entirely in the latest version which is now live, please try it out, thanks
